background = #1b1b1b
foreground = #dddddd
font-family = Menlo
font-size = 13
window-padding-x = 12
window-padding-y = 10
scrollback-limit = 10000000
shell-integration = detect
clipboard-read = deny
clipboard-write = deny
confirm-close-surface = false
