background = #1A1B1D
foreground = #fafafa
font-family = SF Mono, Menlo
font-size = 13
window-padding-x = 0
window-padding-y = 0
scrollback-limit = 10000000
shell-integration = detect
clipboard-read = deny
clipboard-write = deny
confirm-close-surface = false
